// <auto-generated />
using System;
using MatchMaker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchMaker.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241223173728_InitialCreatefirst4")]
    partial class InitialCreatefirst4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GirlId")
                        .HasColumnType("int");

                    b.Property<int>("GuyId")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GirlId");

                    b.HasIndex("GuyId");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("MatchMaker.Core.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Motza")
                        .HasColumnType("int");

                    b.Property<int>("OpennessLevel")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MatchMaker.Core.Entities.Girl", b =>
                {
                    b.HasBaseType("MatchMaker.Core.Entities.Person");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yearbook")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Girl");
                });

            modelBuilder.Entity("MatchMaker.Core.Entities.MatchMaker.Core.Entities.Guy", b =>
                {
                    b.HasBaseType("MatchMaker.Core.Entities.Person");

                    b.Property<int>("Vaad")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Guy");
                });

            modelBuilder.Entity("Idea", b =>
                {
                    b.HasOne("MatchMaker.Core.Entities.Girl", "Girl")
                        .WithMany()
                        .HasForeignKey("GirlId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MatchMaker.Core.Entities.MatchMaker.Core.Entities.Guy", "Guy")
                        .WithMany()
                        .HasForeignKey("GuyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Girl");

                    b.Navigation("Guy");
                });
#pragma warning restore 612, 618
        }
    }
}
